---
name: Benchmark script
author: Didi Hoffmann
description: Runs the benchmark for optimization purposes

services:
  gcb-python:
    image: python:3.9.18
    cmd: sh

flow:
  - name: Running the tests
    container: gcb-python
    commands:
      - type: console
        command: python3 /tmp/repo/python/test.py
        note: Python tests